### ISSUE TITLE
App crashes on Android 11 java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by develogo** [P0cL4bs/Nanobrok#1]
The application crashes right after placing host. When trying to open it again it closes.

Device: Galaxy S21+ 5G
Model: SM-G996B
Android: 11

**Comment by mh4x0f** [comment]
Hi @develogo , thanks for great report, I confirmed this bug on google play report. I 'll check a solution for this bug but i think the problem come from the networkSocket okhttp3.

**Comment by mh4x0f** [comment]
update: I add a patch on google play beta version, checkout!  version: 0.0.6. 
changed:
- upgrade version OkHttp3

thanks again @develogo  for report this bug.

**Comment by mh4x0f** [comment]
@develogo  send me feedback if the problem is solved. I 'm try on Android 11 SDK development and working fine.

**Comment by develogo** [comment]
Is working perfectly. Congratulations on the project, I'm getting my pro version  :D

**Comment by mh4x0f** [comment]
nice, I will fix this bug on Pro version too. thanks again.
